name: Simple Spring Boot CI

on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - master  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Running on the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the repository

    - name: Set up Java JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Set JDK 11 (or use your required version)
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install -DskipTests=true  # Build the project (skipping tests for simplicity)

